/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspacoRouteRouteImport } from './routes/$espaco/route'
import { Route as EspacoIndexRouteImport } from './routes/$espaco/index'
import { Route as EspacoLancamentosIndexRouteImport } from './routes/$espaco/lancamentos/index'
import { Route as EspacoLancamentosIdRouteImport } from './routes/$espaco/lancamentos/$id'
import { Route as EspacoLancamentosNovoRouteImport } from './routes/$espaco/lancamentos/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoRouteRoute = EspacoRouteRouteImport.update({
  id: '/$espaco',
  path: '/$espaco',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoIndexRoute = EspacoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EspacoRouteRoute,
} as any)
const EspacoLancamentosIndexRoute = EspacoLancamentosIndexRouteImport.update({
  id: '/lancamentos/',
  path: '/lancamentos/',
  getParentRoute: () => EspacoRouteRoute,
} as any)
const EspacoLancamentosIdRoute = EspacoLancamentosIdRouteImport.update({
  id: '/lancamentos/$id',
  path: '/lancamentos/$id',
  getParentRoute: () => EspacoRouteRoute,
} as any)
const EspacoLancamentosNovoRoute = EspacoLancamentosNovoRouteImport.update({
  id: '/lancamentos/novo',
  path: '/lancamentos/novo',
  getParentRoute: () => EspacoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$espaco': typeof EspacoRouteRouteWithChildren
  '/$espaco/': typeof EspacoIndexRoute
  '/$espaco/lancamentos/$id': typeof EspacoLancamentosIdRoute
  '/$espaco/lancamentos/novo': typeof EspacoLancamentosNovoRoute
  '/$espaco/lancamentos/': typeof EspacoLancamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$espaco': typeof EspacoIndexRoute
  '/$espaco/lancamentos/$id': typeof EspacoLancamentosIdRoute
  '/$espaco/lancamentos/novo': typeof EspacoLancamentosNovoRoute
  '/$espaco/lancamentos': typeof EspacoLancamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$espaco': typeof EspacoRouteRouteWithChildren
  '/$espaco/': typeof EspacoIndexRoute
  '/$espaco/lancamentos/$id': typeof EspacoLancamentosIdRoute
  '/$espaco/lancamentos/novo': typeof EspacoLancamentosNovoRoute
  '/$espaco/lancamentos/': typeof EspacoLancamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$espaco'
    | '/$espaco/'
    | '/$espaco/lancamentos/$id'
    | '/$espaco/lancamentos/novo'
    | '/$espaco/lancamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$espaco'
    | '/$espaco/lancamentos/$id'
    | '/$espaco/lancamentos/novo'
    | '/$espaco/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/$espaco'
    | '/$espaco/'
    | '/$espaco/lancamentos/$id'
    | '/$espaco/lancamentos/novo'
    | '/$espaco/lancamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspacoRouteRoute: typeof EspacoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$espaco': {
      id: '/$espaco'
      path: '/$espaco'
      fullPath: '/$espaco'
      preLoaderRoute: typeof EspacoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$espaco/': {
      id: '/$espaco/'
      path: '/'
      fullPath: '/$espaco/'
      preLoaderRoute: typeof EspacoIndexRouteImport
      parentRoute: typeof EspacoRouteRoute
    }
    '/$espaco/lancamentos/': {
      id: '/$espaco/lancamentos/'
      path: '/lancamentos'
      fullPath: '/$espaco/lancamentos/'
      preLoaderRoute: typeof EspacoLancamentosIndexRouteImport
      parentRoute: typeof EspacoRouteRoute
    }
    '/$espaco/lancamentos/$id': {
      id: '/$espaco/lancamentos/$id'
      path: '/lancamentos/$id'
      fullPath: '/$espaco/lancamentos/$id'
      preLoaderRoute: typeof EspacoLancamentosIdRouteImport
      parentRoute: typeof EspacoRouteRoute
    }
    '/$espaco/lancamentos/novo': {
      id: '/$espaco/lancamentos/novo'
      path: '/lancamentos/novo'
      fullPath: '/$espaco/lancamentos/novo'
      preLoaderRoute: typeof EspacoLancamentosNovoRouteImport
      parentRoute: typeof EspacoRouteRoute
    }
  }
}

interface EspacoRouteRouteChildren {
  EspacoIndexRoute: typeof EspacoIndexRoute
  EspacoLancamentosIdRoute: typeof EspacoLancamentosIdRoute
  EspacoLancamentosNovoRoute: typeof EspacoLancamentosNovoRoute
  EspacoLancamentosIndexRoute: typeof EspacoLancamentosIndexRoute
}

const EspacoRouteRouteChildren: EspacoRouteRouteChildren = {
  EspacoIndexRoute: EspacoIndexRoute,
  EspacoLancamentosIdRoute: EspacoLancamentosIdRoute,
  EspacoLancamentosNovoRoute: EspacoLancamentosNovoRoute,
  EspacoLancamentosIndexRoute: EspacoLancamentosIndexRoute,
}

const EspacoRouteRouteWithChildren = EspacoRouteRoute._addFileChildren(
  EspacoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspacoRouteRoute: EspacoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
