/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspacoRouteRouteImport } from './routes/$espaco/route'
import { Route as EspacoIndexRouteImport } from './routes/$espaco/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoRouteRoute = EspacoRouteRouteImport.update({
  id: '/$espaco',
  path: '/$espaco',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacoIndexRoute = EspacoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EspacoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$espaco': typeof EspacoRouteRouteWithChildren
  '/$espaco/': typeof EspacoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$espaco': typeof EspacoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$espaco': typeof EspacoRouteRouteWithChildren
  '/$espaco/': typeof EspacoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$espaco' | '/$espaco/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$espaco'
  id: '__root__' | '/' | '/$espaco' | '/$espaco/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspacoRouteRoute: typeof EspacoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$espaco': {
      id: '/$espaco'
      path: '/$espaco'
      fullPath: '/$espaco'
      preLoaderRoute: typeof EspacoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$espaco/': {
      id: '/$espaco/'
      path: '/'
      fullPath: '/$espaco/'
      preLoaderRoute: typeof EspacoIndexRouteImport
      parentRoute: typeof EspacoRouteRoute
    }
  }
}

interface EspacoRouteRouteChildren {
  EspacoIndexRoute: typeof EspacoIndexRoute
}

const EspacoRouteRouteChildren: EspacoRouteRouteChildren = {
  EspacoIndexRoute: EspacoIndexRoute,
}

const EspacoRouteRouteWithChildren = EspacoRouteRoute._addFileChildren(
  EspacoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspacoRouteRoute: EspacoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
